### ISSUE TITLE
Pickling Error in bag.py

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#130]
### What I Did with full Traceback

```
(test-memote)nnfcb-l0232:memote-e-coli clie$ memote report
Writing report 'index.html'
Traceback (most recent call last):
  File "/Users/clie/.virtualenvs/test-memote/bin/memote", line 11, in <module>
    load_entry_point('memote', 'console_scripts', 'memote')()
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/clie/Dev/memote/memote/suite/runner.py", line 293, in report
    file_h.write(report.render_html())
  File "/Users/clie/Dev/memote/memote/suite/reporting/reports/history_report.py", line 83, in render_html
    biomass=self._collect_biomass_plots()
  File "/Users/clie/Dev/memote/memote/suite/reporting/reports/history_report.py", line 108, in _collect_biomass_plots
    df = self.bag.get_biomass_dataframe()
  File "/Users/clie/Dev/memote/memote/suite/reporting/bag.py", line 123, in get_biomass_dataframe
    list.__iadd__, initial=list()).compute(), columns=columns)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/base.py", line 96, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/base.py", line 203, in compute
    results = get(dsk, keys, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/multiprocessing.py", line 87, in get
    dumps=dumps, loads=loads, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/async.py", line 512, in get_async
    fire_task()
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/async.py", line 506, in fire_task
    args=(key, dumps((dsk[key], data)),
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/dask/multiprocessing.py", line 29, in _dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 706, in dumps
    cp.dump(obj)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 150, in dump
    raise pickle.PicklingError(msg)
pickle.PicklingError: Could not pickle object as excessively deep recursion required.```

**Comment by ChristianLieven** [comment]
Seems to happen with Python 2.7. selectively

**Comment by Midnighter** [comment]
Is this still an issue @ChristianLieven ?
