### ISSUE TITLE
`memote report snapshot` raises UnicodeDecodeError on localized Windows 10

### ISSUE THREAD

**Issue by jonovik** [opencobra/memote#348]
When running `memote report snapshot` on the default model on my Windows 10 system using memote 0.5.1, I get a UnicodeDecodeError from encodings/cp1252.py when memote tries to open the html template for the report. Thus, the HTML report never gets written.

From what I can google, the problem is that Python 3 will sometimes [assume the filesystem's default encoding](https://stackoverflow.com/questions/42070668/python-3-default-encoding-cp1252).

The contributing guidelines requests patches to come with tests, but unfortunately I was unable to simulate this error on Linux (CentOS) using `locale.setlocale()`. Nevertheless, I propose a patch below for your consideration.

Steps to reproduce:
Run `memote new` accepting all default suggestions, then `memote report snapshot`. Or use the "more easily debuggable code" below.

<details>
<summary>More easily debuggable code to reproduce the issue</summary>

```python
"""Easily debuggable call to memote, similar to "memote report snapshot"."""

from memote.suite import api
from memote.suite.cli import callbacks


# Adapted from memote/suite/cli/runner.py
model = "model.xml"
filename = "test_memote.html"
pytest_args = []
solver = "glpk"
custom = None, None

model = callbacks.validate_model(None, None, model)

# Adapted from memote/suite/reporting/reports/snapshot.py
model.solver = solver
_, results = api.test_model(model, results=True, pytest_args=pytest_args,
                            custom=custom)
api.snapshot_report(results, filename)
```
</details>

<details>
<summary>Traceback</summary>

```bash
[...snip lots of regular test output...]
======== 37 failed, 40 passed, 13 skipped, 2 warnings in 5.48 seconds =========
>>> api.snapshot_report(results, filename)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\git\memote\memote\suite\api.py", line 135, in snapshot_report
    file_h.write(report.render_html())
  File "C:\git\memote\memote\suite\reporting\reports\snapshot.py", line 55, in render_html
    template = Template(file_handle.read())
  File "C:\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 391134: character maps to <undefined>
```
</details>

<details>
<summary>System Information</summary>

```
Windows 10 version 1709
Python 3.6.3
Locale information from systeminfo.exe:
System Locale:             en-us;English (United States)
Input Locale:              no;Norwegian (Bokmal)
```

```python
import memote
memote.show_versions()
```

```
System Information
==================
OS               Windows
OS-release            10
Python             3.5.2

Package Versions
================
pip                9.0.1
setuptools        36.7.1
memote             0.5.1
cobra              0.9.1
future            0.16.0
swiglpk            1.4.4
optlang            1.2.5
ruamel.yaml      0.14.12
pandas            0.21.0
numpy             1.13.3
python-libsbml    5.15.0
lxml               3.6.4
click                6.7
click-configfile   0.2.3
click-log          0.2.1
pytest             3.2.3
dask              0.15.4
cloudpickle        0.5.1
toolz              0.8.2
Jinja2              2.10
jinja2-ospath      0.2.1
cookiecutter       1.6.0
plotly             2.2.1
```
</details>

<details>
<summary>Proposed patch</summary>

```
Subject: [PATCH] Explicitly set encoding="utf-8" for snapshot report file.
---
 memote/suite/api.py                        | 2 +-
 memote/suite/reporting/reports/snapshot.py | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/memote/suite/api.py b/memote/suite/api.py
index b3e4445..ae46d25 100644
--- a/memote/suite/api.py
+++ b/memote/suite/api.py
@@ -131,7 +131,7 @@ def snapshot_report(results, filename):
     """
     report = SnapshotReport(results)
     LOGGER.info("Writing basic report '%s'.", filename)
-    with io.open(filename, "w") as file_h:
+    with io.open(filename, "w", encoding="utf-8") as file_h:
         file_h.write(report.render_html())
 
 
diff --git a/memote/suite/reporting/reports/snapshot.py b/memote/suite/reporting/reports/snapshot.py
index 3e3b8d7..ff950ff 100644
--- a/memote/suite/reporting/reports/snapshot.py
+++ b/memote/suite/reporting/reports/snapshot.py
@@ -50,8 +50,8 @@ class SnapshotReport(Report):
         to a full Angular based report.
         """
         # template = self.env.get_template("snapshot.html")
-        with io.open(join(dirname(__file__), "../templates/snapshot.html")) as \
-                file_handle:
+        with io.open(join(dirname(__file__), "../templates/snapshot.html"),
+                     encoding="utf-8") as file_handle:
             template = Template(file_handle.read())
         try:
             return template.safe_substitute(
-- 
2.11.0.windows.1
```
</details>

**Comment by Midnighter** [comment]
Thank you for your time in submitting such an extensive error report. I'm glad it seems like an easy fix and I'll apply your patch ASAP.

**Comment by ChristianLieven** [comment]
I've noticed the same errors cropping up when I run `tox` locally in the test_for_api results.

I've applied your patch and at least locally that fixed the errors I got.

**Comment by jonovik** [comment]
Works for me as of 07c091ad. Thanks!
