### ISSUE TITLE
Memote run seems to be broken

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#366]
#### Problem description
I tried running `memote new` with a bunch of models from which I was able to generate functional reports.

#### Code Sample

```bash
memote run e_coli_core.xml
```

```bash
Storing result in 'result.json'.
Traceback (most recent call last):
  File "/Users/clie/.virtualenvs/test-memote/bin/memote", line 11, in <module>
    load_entry_point('memote', 'console_scripts', 'memote')()
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/clie/Dev/memote/memote/suite/cli/runner.py", line 148, in run
    store(result=result)
  File "/Users/clie/Dev/memote/memote/suite/results/result_manager.py", line 88, in store
    raise_with_traceback(error)
  File "/Users/clie/Dev/memote/memote/suite/results/result_manager.py", line 85, in store
    return json.dump(result, file_handle, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: must be unicode, not str
```

### Context

<details>

System Information
==================
OS              Darwin
OS-release      16.7.0
Python          2.7.10

Package Versions
================
pip              9.0.1
setuptools      36.5.0
memote           0.5.1
cobra           0.10.1
future          0.16.0
swiglpk          1.4.4
optlang          1.3.0
ruamel.yaml    0.14.12
pandas          0.22.0
numpy           1.14.0
python-libsbml  5.15.0
lxml             3.8.0
click              6.6
pytest           3.2.2
Jinja2           2.9.6
jinja2-ospath    0.2.1
cookiecutter     1.5.1
numpydoc         0.7.0
</details>

**Comment by Midnighter** [comment]
Can you upgrade to 0.6.1 and see if the problem persists, please?

**Comment by ChristianLieven** [comment]
Ugh, :D Turns out I wasn't in my memote virtual environment when I attached the package versions.

The problem persists on 0.6.1!
