### ISSUE TITLE
TypeError raised with "memote report history"

### ISSUE THREAD

**Issue by bdelepine** [opencobra/memote#374]
#### Problem description

Hi, it's me again,

This time the TypeError is raised in reports.py (see below). This is related (but not identical) to #372 and #370. (This issue is for your information, I don't critically need a fix in the two following weeks).

HTH, best,

#### Code Sample

```bash
$ memote report history path_to_folder
Traceback (most recent call last):
  File "/home/XXX/.miniconda3/envs/gsm/bin/memote", line 11, in <module>
    sys.exit(cli())
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/XXX/.miniconda3/envs/gsm/lib/python3.6/site-packages/memote/suite/cli/reports.py", line 121, in history
    manager = managers.SQLResultManager(location)
TypeError: __init__() takes 1 positional argument but 2 were given

```

### Context

```python
>>> memote.__version__
'0.6.2'
>>> memote.show_versions()

System Information
==================
OS                            Linux
OS-release    3.10.0-693.el7.x86_64
Python                        3.6.4

Package Versions
================
pip                           9.0.1
setuptools                   38.5.2
memote                        0.6.2
cobra                        0.11.3
future                       0.16.0
swiglpk                       1.4.4
optlang                       1.3.0
ruamel.yaml                 0.14.12
pandas                       0.22.0
numpy                        1.14.1
click                           6.7
pytest                        3.4.2
Jinja2                         2.10
jinja2-ospath                 0.2.1
cookiecutter                  1.6.0
numpydoc                      0.7.0
```

**Comment by Midnighter** [comment]
Fix is done. I won't make a release yet, though, since `memote report history` is not fully functional yet. So this fix is kinda pointless until then.
