### ISSUE TITLE
Running `memote history` causes AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#376]
#### Problem description
I executed `memote history` on a model repo and along the previously mentioned SBML errors (https://github.com/opencobra/memote/issues/370), I now get the following traceback every time a distinct test run has started for each commit:

#### Code Sample

```bash
(test-memote)█████:█████████ clie$ memote history
Are you sure that you want to change history? [y/N]: y
```

```bash
Process Process-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/clie/Dev/memote/memote/suite/cli/runner.py", line 184, in _test_history
    manager.store(result, commit=commit)
  File "/Users/clie/Dev/memote/memote/suite/results/repo_result_manager.py", line 129, in store
    filename = self.get_filename(git_info)
  File "/Users/clie/Dev/memote/memote/suite/results/repo_result_manager.py", line 103, in get_filename
    return join(self._backend, "{}.json".format(git_info.hexsha))
  File "/Users/clie/.virtualenvs/test-memote/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
Running the test suite for commit 'c453461bccc9de73f0a94f1e53ae3b24eabe59c3'.
============================================================== test session starts ===============================================================
platform darwin -- Python 2.7.10, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/clie/Dev/memote, inifile: setup.cfg
plugins: rerunfailures-2.2, raises-0.6, cov-2.4.0
collected 107 items                                                                                                                               

../../../../Dev/memote/memote/suite/tests/test_annotation.py FFFFFFFFFFFFFFFFFFFFFFFF.FFFFF.FFFF...
../../../../Dev/memote/memote/suite/tests/test_basic.py .....FFF......F.
../../../../Dev/memote/memote/suite/tests/test_biomass.py .F.......F
../../../../Dev/memote/memote/suite/tests/test_consistency.py FssssssssssssssssFFFFFFFFFF
../../../../Dev/memote/memote/suite/tests/test_matrix.py .....
../../../../Dev/memote/memote/suite/tests/test_sbo.py .........s.

=============================================== 50 failed, 40 passed, 17 skipped in 73.22 seconds ================================================
```

**Comment by Midnighter** [comment]
Sounds like there was no `--location` and it wasn't caught... I ran this without problems yesterday.

**Comment by ChristianLieven** [comment]
Yeah I didn't provide `--location` but there should be a default right?

**Comment by ChristianLieven** [comment]
Just tested it again. Works fine with `--location` provided!

**Comment by Midnighter** [comment]
Well, it always used to be set in the `memote.ini` by the cookiecutter but that is out of date now :/

**Comment by Midnighter** [comment]
Will be handled in #379.
