### ISSUE TITLE
Double check and update all workflows

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#379]
Done: The following workflows have been checked and ideally tests written:

* [x] `memote run`
* [x] `memote new`
* [x] `memote online`
* [x] `memote save`
* [x] `memote history`
* [x] `memote report history`

**Comment by Midnighter** [comment]
* `memote save` removed. We expect users to learn basic git commands.
* `memote history` tested on minimal repository.

**Comment by ChristianLieven** [comment]
I've tested `memote history` on my methylococcus repo (https://github.com/ChristianLieven/memote-m-capsulatus) with the following error:

shell```
(test-memote) nnfcb-l0232:memote-m-capsulatus clie$ git branch
  develop
  gh-pages
* master
(test-memote) nnfcb-l0232:memote-m-capsulatus clie$ ls
AUTHORS.rst		HISTORY.rst		README.md		requirements.txt
CONTRIBUTING.rst	LICENSE			Results			scripts
ComplementaryData	MetabolicMap		index.html		tox.ini
ComplementaryScripts	ModelFiles		memote.ini		tox_install.sh
(test-memote) nnfcb-l0232:memote-m-capsulatus clie$ memote history --rewrite
Traceback (most recent call last):
  File "/anaconda/envs/test-memote/bin/memote", line 11, in <module>
    load_entry_point('memote', 'console_scripts', 'memote')()
  File "/anaconda/envs/test-memote/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda/envs/test-memote/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/anaconda/envs/test-memote/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda/envs/test-memote/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda/envs/test-memote/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/clie/Dev/memote/memote/suite/cli/runner.py", line 268, in history
    history.load_history()
  File "/Users/clie/Dev/memote/memote/suite/results/history_manager.py", line 107, in load_history
    self._results[commit] = self.manager.load(commit)
  File "/Users/clie/Dev/memote/memote/suite/results/repo_result_manager.py", line 136, in load
    filename = self.get_filename(git_info)
  File "/Users/clie/Dev/memote/memote/suite/results/repo_result_manager.py", line 103, in get_filename
    return join(self._backend, "{}.json".format(git_info.hexsha))
  File "/anaconda/envs/test-memote/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ChristianLieven** [comment]
`memote report diff` and `memote report snapshot` btw seem to work as expected in their most basic invocations!

**Comment by Midnighter** [comment]
`memote history` requires the location of where results are stored (either directory or sqlite database at the moment).
