### ISSUE TITLE
Replace formula id check with MetaNetX id check

### ISSUE THREAD

**Issue by siddC** [opencobra/memote#381]
#### Problem description

Currently, `find_oxygen_reactions` in `basic.py` uses `met.formula == "O2"` to check for reactions containing oxygen. This needs to be changed to use MetaNetX ID as many models may have a blank formula field.

**Comment by ChristianLieven** [comment]
I wouldn't change it entirely i.e. replace one with the other, but rather have both in sequence. Take a look at how we identify the biomass reaction to get an idea of what I mean.

**Comment by siddC** [comment]
Updating `scripts/generate_mnx_shortlists.py` with the MNX id for oxygen and running the script returns a `FileNotFoundError` exception. Traceback below in details. It seems like `chem_xref.tsv` should be included in the scripts folder but isn't, which is causing this error.

<Details>

~~~
(memote-ZVtwQ_6J) bash-3.2$ python scripts/generate_mnx_shortlists.py 
Traceback (most recent call last):
  File "scripts/generate_mnx_shortlists.py", line 39, in <module>
    names=['XREF', 'MNX_ID', 'Evidence', 'Description'])
  File "/Users/sidcha/.local/share/virtualenvs/memote-ZVtwQ_6J/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/sidcha/.local/share/virtualenvs/memote-ZVtwQ_6J/lib/python3.6/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/sidcha/.local/share/virtualenvs/memote-ZVtwQ_6J/lib/python3.6/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/Users/sidcha/.local/share/virtualenvs/memote-ZVtwQ_6J/lib/python3.6/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/sidcha/.local/share/virtualenvs/memote-ZVtwQ_6J/lib/python3.6/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'chem_xref.tsv' does not exist
~~~

</Details>

**Comment by ChristianLieven** [comment]
Hey Sidd, The script looks for "chem_xref.tsv" in the same directory as where it is executed. This can be anywhere on your machine, depending on where you run the script, for instance I personally run it from a jupyter notebook that I have for memote testing. 

We have decided against including the `chem_xref.tsv` because it is a very large database dump that is no longer needed once the script has run.

**Comment by siddC** [comment]
So I updated `scripts/generate_mnx_shortlists.py` with the MNX id for oxygen (MNXM4) and successfully ran it to update `data/met_id_shortlist.json`. However running `tox -e py36` revealed an unusual error. `detect_energy_generating_cycles` raised an RuntimeError with the message:

```E           RuntimeError: MNXM20 is not in the MetaNetX Shortlist! Make sure you typed the ID correctly, if yes, update the shortlist by updating and re-running the script generate_mnx_shortlists.py.```

However, MXNM20 was never in the MetaNetX Shortlist so I'm not sure why this is happening. The full traceback is in the Details tab below.


<Details>

~~~
=============================== FAILURES ================================
 test_detect_energy_generating_cycles_control_flow[glpk-produces_glu-MNXM89557] 

model = <Model produces_glu at 0x1164779b0>, metabolite_id = 'MNXM89557'

    @pytest.mark.parametrize("model, metabolite_id", [
        # test control flow statements
        ("produces_atp", 'MNXM3'),
        ("produces_accoa", 'MNXM21'),
        ("produces_fadh2", "MNXM38"),
        ("produces_glu", "MNXM89557"),
        ("produces_nadh", "MNXM10"),
        ("maintenance_present", "MNXM3"),
    ], indirect=["model"])
    def test_detect_energy_generating_cycles_control_flow(model, metabolite_id):
        """Expect that energy-generating cycles don't exist for metabolite ID."""
>       cycle = consistency.detect_energy_generating_cycles(model, metabolite_id)

tests/test_for_support/test_for_consistency.py:607: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
memote/support/consistency.py:357: in detect_energy_generating_cycles
    main_comp)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

model = <Model produces_glu at 0x1164779b0>, mnx_id = 'MNXM20'
compartment_id = 'c'

    def find_met_in_model(model, mnx_id, compartment_id=None):
        """
        Identify metabolites in the model by looking up IDs in METANETX_SHORTLIST.
    
        Parameters
        ----------
        model : cobra.Model
            A cobrapy metabolic model
        mnx_id : string
            Memote internal MetaNetX metabolite identifier used to map between
            cross-references in the METANETX_SHORTLIST.
        compartment_id : string, optional
            ID of the specific compartment where the metabolites should be found.
            Defaults to returning matching metabolites from all compartments.
    
        Returns
        -------
        list of cobra.Metabolite
    
        """
        if mnx_id not in METANETX_SHORTLIST.columns:
            raise RuntimeError("{} is not in the MetaNetX Shortlist! Make sure "
                               "you typed the ID correctly, if yes, update the "
                               "shortlist by updating and re-running the script "
>                              "generate_mnx_shortlists.py.".format(mnx_id))
E           RuntimeError: MNXM20 is not in the MetaNetX Shortlist! Make sure you typed the ID correctly, if yes, update the shortlist by updating and re-running the script generate_mnx_shortlists.py.

memote/support/helpers.py:594: RuntimeError
------------------------- Captured stdout setup -------------------------
unknown metabolite 'a' created
unknown metabolite 'b' created
unknown metabolite 'c' created
unknown metabolite 'glu__L_c' created
unknown metabolite 'h2o_c' created
unknown metabolite 'akg_c' created
unknown metabolite 'nh3_c' created
unknown metabolite 'h_c' created
=========================== warnings summary ============================
tests/test_for_suite/test_for_api.py::test_snapshot_report_file[glpk-complete_failure]
  /Users/sidcha/Documents/projects/memote/memote/suite/api.py:98 UnsafeLoaderWarning: 
  The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
  Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
  Alternatively include the following in your code:
  
    import warnings
    warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
  
  In most other cases you should consider using 'safe_load(stream)'

tests/test_for_suite/test_for_cli/test_for_reports.py::test_snapshot[ecoli-core]
  /Users/sidcha/Documents/projects/memote/memote/suite/reporting/config.py:57 UnsafeLoaderWarning: 
  The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
  Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
  Alternatively include the following in your code:
  
    import warnings
    warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)
  
  In most other cases you should consider using 'safe_load(stream)'

-- Docs: http://doc.pytest.org/en/latest/warnings.html
 1 failed, 290 passed, 1 skipped, 2 xfailed, 2 warnings in 20.34 seconds 
ERROR: InvocationError: '/Users/sidcha/Documents/projects/memote/.tox/py36/bin/pytest --cov=memote'
________________________________ summary ________________________________
ERROR:   py36: commands failed
(memote-ZVtwQ_6J) bash-3.2$ 
~~~

</Details>

**Comment by Midnighter** [comment]
Did running the script update the IDs in unexpected ways?

**Comment by siddC** [comment]
Possibly, but I can't be sure, since the diff for the json file was 1 insertion and 1 deletion with the whole file in question

**Comment by siddC** [comment]
Update: adding MNXM20 to the script file resolved all issues.
