### ISSUE TITLE
Issue installing memote

### ISSUE THREAD

**Issue by adjurhuus** [opencobra/memote#747]
I've been trying to install memote in a conda environment, using both pip install and git.
It installs without giving any errors in both cases, but when I try to run memote it gives me the following error;

Traceback (most recent call last):
  File "/home/ad/.local/bin/memote", line 5, in <module>
    from memote.suite.cli.runner import cli
  File "/home/ad/.local/lib/python3.10/site-packages/memote/__init__.py", line 36, in <module>
    from memote.suite.api import *
  File "/home/ad/.local/lib/python3.10/site-packages/memote/suite/api.py", line 30, in <module>
    from memote.suite.collect import ResultCollectionPlugin
  File "/home/ad/.local/lib/python3.10/site-packages/memote/suite/collect.py", line 28, in <module>
    from memote.support.helpers import find_biomass_reaction
  File "/home/ad/.local/lib/python3.10/site-packages/memote/support/helpers.py", line 32, in <module>
    from importlib_resources import open_text
ImportError: cannot import name 'open_text' from 'importlib_resources' (/home/ad/.local/lib/python3.10/site-packages/importlib_resources/__init__.py)

I've tried updating importlib_resources, which says it's up to date, and I've tried using different versions of python, both 3.10 and 3.7, but it gives the same error.

**Comment by Midnighter** [comment]
Please `pip install 'importlib_resources <1.0' for now.

**Comment by adjurhuus** [comment]
That fixed the problem, thank you!
