### ISSUE TITLE
Running memote

### ISSUE THREAD

**Issue by SoleilSu** [opencobra/memote#748]
I am running memote in my conda environment, and I got an import error: `ImportError: cannot import name 'open_text' from 'importlib_resources'` Then I reinstalled the packages as suggested `pip install 'importlib_resources <1.0'`. And I got a new error.

```
Traceback (most recent call last):
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/bin/memote", line 5, in <module>
    from memote.suite.cli.runner import cli
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/memote/suite/cli/runner.py", line 45, in <module>
    import memote.suite.cli.callbacks as callbacks
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/memote/suite/cli/callbacks.py", line 30, in <module>
    from memote.experimental import ExperimentConfiguration
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/memote/experimental/__init__.py", line 22, in <module>
    from memote.experimental.config import *
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/memote/experimental/config.py", line 29, in <module>
    from jsonschema import Draft4Validator
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/jsonschema/__init__.py", line 17, in <module>
    from jsonschema.validators import (
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/jsonschema/validators.py", line 19, in <module>
    from jsonschema_specifications import REGISTRY as SPECIFICATIONS
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/jsonschema_specifications/__init__.py", line 7, in <module>
    from jsonschema_specifications._core import _schemas
  File "/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/jsonschema_specifications/_core.py", line 10, in <module>
    from importlib_resources import files  # type: ignore
ImportError: cannot import name 'files' from 'importlib_resources' (/local/workdir/ls764/metaGEM/workflow/envs/metaG/lib/python3.8/site-packages/importlib_resources/__init__.py)
```

**Comment by sreerampeela** [comment]
Hi.. Have you resolved this error? I am getting the same error.

**Comment by Midnighter** [comment]
Let's keep this open so I have a reference tomorrow when I want to fix this.
